config/routes.rb
Qaror::Application.routes.draw do

  resources :pages

  #
  # admin
  #
  namespace :admin do
    root :to => "main#index"
    resources :main do
      collection do
        get 'thrs'
        get 'ans'
        get 'comments'
      end
    end
    resources :activities do
      collection do
        get 'reported'
      end
    end
    resources :pages
    resources :stats
    resources :badges
    resources :users
    resources :contact_us
  end

  match '/auth/:provider/callback' => 'login#create'
  match '/auth/failure' => 'login#failure'

  resources :search do
    collection do
      get 'tags'
    end
  end

  resources :achievements, :path => "/achievements"

  resources :comments
  match '/comments/:id/vote/:vote',:to=>'comments#vote', :as => :vote_comments

  resources :tags
  match '/tags/sort/:sort', :to => 'tags#index', :as => :tags_sort
  match '/tags/:id/:sort', :to => 'tags#show', :as => :tag_sort

  resources :ans, :path => "/answers" do
    resources :comments

    member do
      put 'edit'
      get 'report_flag'
      put 'flag'
      get 'history'
    end
  end

  match '/answers/:id/resolved' => 'ans#resolved', :as => :resolved_an
  match '/answers/:id/unresolved' => 'ans#unresolved', :as => :unresolved_an
  match '/answers/:id/vote/:vote',:to=>'ans#vote', :as => :vote_ans

  match '/questions/:id/sort/:sort',:to=>'thrs#show', :as => :ans_sort


  resources :thrs, :path => "/questions" do
    resources :comments
    member do
      put 'edit'
      get 'fav'
      get 'report_close'
      get 'report_flag'
      post 'answer'
      put 'close'
      put 'flag'
      put 'reopen'
      put 'subscribe'
      get 'history'
    end
  end
  match '/questions/:id/vote/:vote',:to=>'thrs#vote', :as => :vote_thrs
  match '/questions/sort/:sort', :to => 'thrs#index', :as => :thrs_sort

  resources :login

  match '/users/profile', :to=> 'users#update', :via => :put
  match '/users/profile', :to=> 'users#edit', :via => :get, :as=>:profile
  resources :users, :path => "/users" do
    collection do
      get 'activate'
      get 'remind_password_edit'
      post 'remind_password'
      get 'change_password'
      post 'change_password'
      get 'ako'
    end
    member do
      get 'send_activation_link'
      get 'activity'
      get 'reputation'
      get 'votes'
      get 'favorites'
    end
  end

  match '/contact' => 'main#pages', :as => :contact_us
  match '/faq' => 'main#pages', :as => :faq
  match '/privacy' => 'main#pages', :as => :privacy
  match '/privileges' => 'pages#privileges', :as => :privileges
  
  match '/remind_password', :to => 'users#remind_password_edit',:as=>:remind_password
  match '/register', :to => 'users#new',:as => :register
  match '/login', :to => 'login#index',:as => :login
  match '/logout', :to => 'login#logout',:as => :logout
#  match '/wp', :to=> 'main#wiki_parser', :as=>:wiki_parser
  root :to => 'thrs#index'

end

app/models/comment.rb
# encoding: utf-8

class Comment < ActiveRecord::Base
  include Extender::Voteable
  before_create { self.activity_at = Time.now }

  STATUS_NEW = 0
  STATUS_ACTIVE = 1
  STATUS_DELETED = 9

  has_many :activities, :as => :activityable
  accepts_nested_attributes_for :activities
  
  belongs_to :commentable, :polymorphic => true
  belongs_to :user

  attr_accessible :content

  validates :content,
            :presence => true,
            :length => {:within => 10..500}

  scope :active, where(:status => STATUS_ACTIVE)
  scope :deleted, where(:status => STATUS_DELETED)
  scope :sortable, lambda { |sort=nil|
    case sort
    when "oldest" then order("created_at ASC")
    when "votes" then order("(vote_up + vote_down) DESC")
    else
      order("activity_at ASC")
    end
  }
  
  def stitle
    status_string + content
  end

  def status_string
    case self[:status]
#    when STATUS_ACTIVE then '[active] '
    when STATUS_DELETED then '[usunięta] '
    else ''
    end
  end

  def mark_as_destroy
    self.status = STATUS_DELETED
    self.save(:validate => false)
  end
  
protected


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  authorize_resource

  # GET /comments
  # GET /comments.xml
  def index
    @commentable = find_commentable
    @comments = @commentable.comments.active

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])
    @commentable = find_commentable

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new

    @commentable = find_commentable
    @comment = Comment.new
    respond_to do |format|
      format.html # new.html.erb
      format.js # new.html.erb
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.active.find(params[:id])
    @commentable = find_commentable
  end

  # POST /comments
  # POST /comments.xml
  def create

    @commentable = find_commentable
    @comment = @commentable.comments.build #(params[:comment])

    @comment.content = params[:comment][:content]
    @comment.user_id = current_user.id
    Extender::Activities.create(@comment,current_user)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment) }
        format.js {
          @comments = @commentable.comments.active
        }
      else
        format.html { render :action => "new" }
        format.js { render :action => "new" }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.active.find(params[:id])
    @commentable = @comment.commentable
    @comment.content = params[:comment][:content]    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment) }
        format.js { 
          @comments = @commentable.comments.active
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.js { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.active.find(params[:id])
    @commentable = @comment.commentable
    Extender::Activities.delete(@comment,current_user)
    @comment.mark_as_destroy

    respond_to do |format|
#      format.html { redirect_to(comments_url) }
      format.js {
        @comments = @commentable.comments.active
      }
    end
  end

  def vote
    @comment = Comment.active.find(params[:id])

    params[:vote] == 'up' ? authorize!(:vote_up,Comment) : authorize!(:vote_down,Comment)

    respond_to do |format|
      if vote = @comment.vote(current_user,params[:vote])
        format.html { redirect_to(request.referer) }
        format.js
      else
        format.html { redirect_to(request.referer) }
        format.js { render_flash_window :content => @comment.errors[:base].first }
      end
    end
  end

private

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  

end

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment], :html => { :class => 'remote-submit' } do |f| %>
  <div>
    <div class="left">
      <%= f.text_area :content,:size=>'70x1' %>
    </div>
    <div class="left" style="margin-left:5px;width:140px;">
      <%= f.submit t(:save),:class=> 'ui_button small',:style => 'margin-top:1px;margin-bottom:2px;' %>
      <%= link_to t(:close),'', :class=> '_close_comment ui_button small' %>
    </div>
    <div class="clear"></div>
  </div>
  <div>
    <%= field_messages_for @comment %>
  </div>
  
<% end %>

app/views/comments/_list.html.erb
<div class="list">
  <% @comments.each do |comment| %>
    <div id="comment-<%= comment.id %>" class="comment" >
      <% if can? :edit, comment %>
        <span class="comment_options">
          <%#*send(:"edit_#{comment.commentable.class.name.downcase}comment_url",1,2)%>
          <%= link_to t(:edit), edit_comment_url(comment),:id=>'edit_comment',:class=>'small_font' %> |
          <%= link_to t(:destroy), comment, :class=> '_confirm-remote-delete small_font',"data-confirmation" => 'czy chcesz usunac komentarz ?' %>
        </span>
      <% end %>
      <%# if can? :vote, comment %>
        <%#= render :partial=> 'shared/vote', :locals => { :object => comment }  %>
      <%# end %>
      <span class="content"><%= comment.content %></span>&nbsp; &mdash; &nbsp;<%= user_label_small(comment.user) %>
      <span class="created_at small_font"><%= distance_of_time_in_words_to_now(comment.created_at) %></span>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %>.comments .new_comment_a').show();
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %>.comments .new_comment').hide();
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %>.comments .list').replaceWith('<%= escape_javascript(render ('list') ) %>');

app/views/comments/destroy.js.erb
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %>.comments .list').replaceWith('<%= escape_javascript(render ('list') ) %>');

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/edit.js.erb
$('#comment-<%= @comment.id %>').html('<%= escape_javascript(render 'form') %>');
$("#comment_content").autoGrow();

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %> .new_comment_a').hide();
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %> .new_comment').show().parent().children('.new_comment').html('<%= escape_javascript(render ('form') ) %>');
$("#comment_content").autoGrow();

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/update.js.erb
$('#<%= @commentable.class.name.downcase %>-<%= @commentable.id %>.comments .list').replaceWith('<%= escape_javascript(render ('list') ) %>');

app/views/comments/vote.js.erb
$('#<%= @comment.class.name.downcase %>-<%= @comment.id %> .votes').replaceWith('<%= escape_javascript(
  render(:partial=>'shared/vote',:locals => { :object => @comment })
) %>');