config/routes.rb
Qaror::Application.routes.draw do

  resources :pages

  #
  # admin
  #
  namespace :admin do
    root :to => "main#index"
    resources :main do
      collection do
        get 'thrs'
        get 'ans'
        get 'comments'
      end
    end
    resources :activities do
      collection do
        get 'reported'
      end
    end
    resources :pages
    resources :stats
    resources :badges
    resources :users
    resources :contact_us
  end

  match '/auth/:provider/callback' => 'login#create'
  match '/auth/failure' => 'login#failure'

  resources :search do
    collection do
      get 'tags'
    end
  end

  resources :achievements, :path => "/achievements"

  resources :comments
  match '/comments/:id/vote/:vote',:to=>'comments#vote', :as => :vote_comments

  resources :tags
  match '/tags/sort/:sort', :to => 'tags#index', :as => :tags_sort
  match '/tags/:id/:sort', :to => 'tags#show', :as => :tag_sort

  resources :ans, :path => "/answers" do
    resources :comments

    member do
      put 'edit'
      get 'report_flag'
      put 'flag'
      get 'history'
    end
  end

  match '/answers/:id/resolved' => 'ans#resolved', :as => :resolved_an
  match '/answers/:id/unresolved' => 'ans#unresolved', :as => :unresolved_an
  match '/answers/:id/vote/:vote',:to=>'ans#vote', :as => :vote_ans

  match '/questions/:id/sort/:sort',:to=>'thrs#show', :as => :ans_sort


  resources :thrs, :path => "/questions" do
    resources :comments
    member do
      put 'edit'
      get 'fav'
      get 'report_close'
      get 'report_flag'
      post 'answer'
      put 'close'
      put 'flag'
      put 'reopen'
      put 'subscribe'
      get 'history'
    end
  end
  match '/questions/:id/vote/:vote',:to=>'thrs#vote', :as => :vote_thrs
  match '/questions/sort/:sort', :to => 'thrs#index', :as => :thrs_sort

  resources :login

  match '/users/profile', :to=> 'users#update', :via => :put
  match '/users/profile', :to=> 'users#edit', :via => :get, :as=>:profile
  resources :users, :path => "/users" do
    collection do
      get 'activate'
      get 'remind_password_edit'
      post 'remind_password'
      get 'change_password'
      post 'change_password'
      get 'ako'
    end
    member do
      get 'send_activation_link'
      get 'activity'
      get 'reputation'
      get 'votes'
      get 'favorites'
    end
  end

  match '/contact' => 'main#pages', :as => :contact_us
  match '/faq' => 'main#pages', :as => :faq
  match '/privacy' => 'main#pages', :as => :privacy
  match '/privileges' => 'pages#privileges', :as => :privileges
  
  match '/remind_password', :to => 'users#remind_password_edit',:as=>:remind_password
  match '/register', :to => 'users#new',:as => :register
  match '/login', :to => 'login#index',:as => :login
  match '/logout', :to => 'login#logout',:as => :logout
#  match '/wp', :to=> 'main#wiki_parser', :as=>:wiki_parser
  root :to => 'thrs#index'

end

app/models/thr.rb
# encoding: utf-8
class Thr < ActiveRecord::Base
  extend FriendlyId

  has_paper_trail :only => [:title,:content,:tagnames], :on=> [:update], :meta => {
    :user_id  => Proc.new { |m| m.updated_by.id },
    :summary  => Proc.new { |m| m.vsummary if m.changed? && !m.vsummary.blank? }
  }
  
  include Extender::Voteable
  include Extender::Impressionable
  include Extender::Taggable

  before_create { self.activity_at = Time.now }

  MAX_ATTACHES = 4

  STATUS_NEW = 0
  STATUS_ACTIVE = 1
  STATUS_CLOSED = 3
  STATUS_HIDDEN = 8
  STATUS_DELETED = 9

  friendly_id :title, use: :slugged

  has_many :ans,:dependent => :destroy
  has_many :attaches,:as => :attachable, :dependent => :destroy
  has_many :comments,:as => :commentable, :dependent => :destroy
  has_many :activities, :as => :activityable# never destroy user activities
  accepts_nested_attributes_for :activities

  has_many :subscriptions,:as => :subscribable, :dependent => :destroy

  belongs_to :user

  apply_simple_captcha

  attr_accessor :accessible,:add_attaches,:vsummary,:updated_by
  attr_accessible :title, :content, :tagnames

  validates :title,
            :presence => true,
            :length => {:within => 10..100},
            :uniqueness => { :case_sensitive => false }

  validates :content,
            :presence => true,
            :length => {:within => 20..3000}

  after_create :set_subscription


  scope :active, where(:status => STATUS_ACTIVE)
  scope :closed, where(:status => STATUS_CLOSED)
  scope :active_or_closed, where(:status => [STATUS_ACTIVE,STATUS_CLOSED])
  scope :deleted, where(:status => STATUS_DELETED)
  scope :hidden_or_deleted, where(:status => [STATUS_HIDDEN,STATUS_DELETED])
#  scope :users_favorit, where(:status => STATUS_DELETED)
  scope :releated, lambda { |thr|
      select("thrs.id,thrs.title,thrs.slug").joins(:tags).
      where({:tags=>{:name.matches_any=> thr.tags.map(&:name)}}).
      where({:thrs=>{:id.not_eq=>thr.id}}).
      group("thrs.id,thrs.title").limit(20)
  }

  scope :sortable, lambda { |sort=nil|
    case sort
    when "newest" then order("created_at DESC")
    when "hot" then order("hotness DESC")
    else
      order("activity_at DESC")
    end
  }

  def users_fav
    activities.favs
  end

  def stitle
    status_string + title
  end

  def status_string
    case self[:status]
#    when STATUS_ACTIVE then '[active] '
    when STATUS_CLOSED then '[closed] '
    when STATUS_HIDDEN then '[hidden] '
    when STATUS_DELETED then '[deleted] '
    else ''
    end
  end

  def closed?
    status == STATUS_CLOSED
  end

  def mark_as_destroyed?
    status == STATUS_DELETED
  end

  def resolved?
    ans.map(&:resolved).include? An::RESOLVED
  end

  def last_activity_user
    User.find_by_id(last_activity_user_id)
  end

  def last_activity
    Activity.find_by_id(last_activity_id)
  end

  def subscribed?(user_id)
    subscriptions.where(:user_id=>user_id).first
  end

  def subscribe(user_id)
    if sub = subscribed?(user_id)
      sub.destroy
      sub = nil
    else
      sub = subscriptions.create(:user_id=>user_id)
    end
  end

  def mark_as_closed
    self.status = STATUS_CLOSED
    self.save
  end

  def mark_as_hidden_if_needed
    if self.activities.flagged.count >= APP_VOTING_CONFIG['flags_to_hide_post']
      self.status = STATUS_HIDDEN
      self.save
    else
      self.save
    end
  end

  def mark_as_destroy
    self.status = STATUS_DELETED
    self.save(:validate => false)
  end

  def vsummary
    version.summary if !live?
  end

private

  def set_subscription
    self.subscriptions.find_or_create_by_user_id(user_id)
  end

#
# => W RAZIE GDY BY POTRZEBA ZALACZNIKOW BEZPOSREDNIO W THR
#
#  def check_add_attaches
#    if @add_attaches.respond_to?('each')
#      errors.add(:attach,"za duzo obrazkow maksymalnie " + MAX_ATTACHES.to_s) if @add_attaches.count > MAX_ATTACHES
#    end
#  end
#  def set_attaches
#    if @add_attaches
#        Array(@add_attaches).map do |a|
#          if attach = Attach.where(:user_id=>user_id).find(a)
#            attach.thr_id = self.id
#            attach.status = Attach::STATUS_ASSIGN
#            attach.save
#          end
#        end
#    end
#  end

  def mass_assignment_authorizer
    if accessible == :all
      self.class.protected_attributes
    else
      super + (accessible || [])
    end
  end

end

app/controllers/thrs_controller.rb
class ThrsController < ApplicationController

  authorize_resource :except => :index

  
  def index
    
    respond_to do |format|
      format.html {
        @tag_thr = Thr.joins(:tags).group("tags.name").limit(10).count(:id)
        @users = User.order("created_at DESC").limit(8)
        @thrs = Thr.active_or_closed.sortable(params[:sort]).paginate(:per_page=>default_per_page,:page=>params[:page])
        @achievements = Achievement.order("created_at DESC").limit(15)
      }
      format.json {
        @thrs = Thr.active_or_closed.sortable(params[:sort]).limit(5)
        render json: @thrs
      }
    end
  end

  def show

    show_action

    respond_to do |format|
      format.html # show.html.erb
      format.js { render 'schema' }
    end
  end

  def new
    
    @thr = Thr.new
    if session[:thr]
      @thr.title = session[:thr][:title]
      @thr.content = session[:thr][:content]
      @thr.tagnames = session[:thr][:tagnames]
    end
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @thr = Thr.find(params[:id])
    
#    p @thr
    if !params[:version].blank?
      restore_version = @thr.versions[params[:version].to_i]
      if restore_version
        @thr = @thr.version_at(restore_version.created_at - 3.seconds)
        @current_version = restore_version.index
      end
    else
      @current_version = @thr.versions.count
    end
  end

  def create

    @thr = Thr.new
    @thr.title = params[:thr][:title]
    @thr.content = params[:thr][:content]
    @thr.tagnames = params[:thr][:tagnames]
    @thr.add_attaches = params[:attaches]
    @thr.user_id = current_user.id if current_user

    @thr.captcha = params[:thr][:captcha]
    @thr.captcha_key = params[:thr][:captcha_key]

    respond_to do |format|
      # kolejnosc ma znaczenie
      if !@thr.valid_with_captcha? && cannot?(:skip_captcha,Thr)
        format.html { render :action => "new" }
      else
        Extender::Activities.create(@thr,current_user) if current_user
        if current_user && @thr.save
          session[:thr] = nil
          @thr.to_param
          format.html { redirect_to(@thr, :notice => t('thrs.create.saved')) }
        elsif !current_user && @thr.valid?
          session[:thr] = params[:thr]
          format.html { redirect_to(login_index_url, :notice => t(:question_stored)) }
        else
          format.html { render :action => "new" }
        end
      end
    end
  end

  def update
    @thr = Thr.find(params[:id])

    @thr.title = params[:thr][:title] if can?(:edit, @thr)
    @thr.content = params[:thr][:content] if can?(:edit, @thr)
    @thr.tagnames = params[:thr][:tagnames]
    @thr.vsummary = params[:thr][:vsummary]
    @thr.add_attaches = params[:attaches] if can?(:edit, @thr)
    @thr.updated_by = current_user
    Extender::Activities.revise(@thr,current_user) if @thr.changed?
    respond_to do |format|
      if @thr.save
        format.html { redirect_to(@thr, :notice => t('thrs.update.saved')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @thr = Thr.find(params[:id])
    Extender::Activities.delete(@thr,current_user)
    respond_to do |format|
      if @thr.mark_as_destroy
        format.html { redirect_to(request.referer) }
        format.js { render :text=>'location.reload();' }
      else
        format.html { redirect_to(request.referer) }
        format.js { render_flash_window :content => unified_errors(@thr) }
      end
    end
  end

  def answer
    
    show_action

    if request.post?
      @thr = Thr.active.find(params[:an][:thr_id])

      @an = An.new
      @an.thr_id = params[:an][:thr_id]
      @an.content = params[:an][:content]
      @an.user_id = current_user.id if current_user
      Extender::Activities.create(@an,current_user) if current_user

      @an.captcha = params[:an][:captcha]
      @an.captcha_key = params[:an][:captcha_key]

    end
    
#    respond_to do |format|
      if request.post? && @an.valid_with_captcha? && cannot?(:skip_captcha,An)
        render 'show'
      else
        if request.post? && current_user && @an.save
          session[:an] = nil
          redirect_to( thr_url(@thr,:anchor=> 'an-' + @an.id.to_s), :notice => t("ans.create.saved"))
        elsif request.post? && !current_user && @an.valid?
          session[:an] = params[:an]
          redirect_to(login_index_url, :notice => t(:answer_stored))
        else
          render 'show'
        end
#      end
    end

  end

  def tagged
    
  end

  def vote
    @thr = Thr.find(params[:id])

    params[:vote] == 'up' ? authorize!(:vote_up,Thr) : authorize!(:vote_down,Thr)

    respond_to do |format|
      if vote = @thr.vote(current_user,params[:vote])
        format.html { redirect_to(request.referer) }
        format.js
      else
        format.html { redirect_to(request.referer) }
        format.js { render_flash_window :content => unified_errors(@thr) }
      end
    end
  end

  def fav
    @thr = Thr.find(params[:id])
    Extender::Activities.fav(@thr, current_user)

    respond_to do |format| 
      format.html { redirect_to(request.referer) }
      format.js
    end
  end

  def history
    @thr = Thr.find(params[:id])
    @versions = @thr.versions.order("number DESC").paginate(:per_page=>default_per_page,:page=>params[:page])
  end

  def report_close
    @thr = Thr.active.find(params[:id])
  end

  def report_flag
    @thr = Thr.active_or_closed.find(params[:id])
  end

  def close
    @thr = Thr.active.find(params[:id])
    Extender::Activities.close(@thr, current_user,params[:acomment])
    respond_to do |format|
      if @thr.mark_as_closed
        format.html { redirect_to(request.referer) }
        format.js
      else
        format.html { redirect_to(request.referer) }
        format.js { render_flash_window :content => unified_errors(@thr) }
      end
    end
  end

  def flag
    @thr = Thr.active_or_closed.find(params[:id])
    Extender::Activities.flag(@thr, current_user,params[:acomment])
    respond_to do |format|
      if @thr.mark_as_hidden_if_needed
        format.html { redirect_to(request.referer) }
        format.js
      else
        format.html { redirect_to(request.referer) }
        format.js { render_flash_window :content => unified_errors(@thr) }
      end
    end
  end

  def reopen
    @thr = Thr.closed.find(params[:id])
    @thr.status = Thr::STATUS_ACTIVE
    respond_to do |format|
      if @thr.save
        format.html { redirect_to(request.referer) }
        format.js
      else
        format.html { redirect_to(request.referer) }
        format.js
      end
    end
  end

  def subscribe
    @thr = Thr.find(params[:id])
    @subscribe = @thr.subscribe(current_user.id)
    respond_to do |format|
        format.html { redirect_to(request.referer) }
        format.js
    end
  end

private

  def show_action
    @thr = Thr.find(params[:id])

#    @thr.increment!(:hits)
    @thr.log_impression(request.remote_ip,current_user)

    if current_user
      @subscribe = @thr.subscriptions.where(:user_id=>current_user.id).first
      if @subscribe
        @subscribe.last_view = Time.now
        @subscribe.save
      end
    end

    @related_thrs = Thr.releated(@thr)
    @tag_thr = Thr.grouped_tags(@thr)

    @comment = Comment.new

    @an = An.new
    if session[:an]  
      @an.thr_id = session[:an][:thr_id]
      @an.content = session[:an][:content]
    end
    
    @ans = @thr.ans.active.sortable(params[:sort])
    
  end


end

app/helpers/thrs_helper.rb
module ThrsHelper
end

app/views/thrs/_form_retag.html.erb
<%= form_for(@thr) do |f| %>
  <%= f.hidden_field :vsummary, :value => 'przetagowanie' %>
  <div class="field">
    <div id="tags_preview"></div>
    <%= f.label :tagnames %>
    <%= f.text_field :tagnames,:id=>:tagit %>
  </div>
  <div class="field">
    <%= field_messages_for @thr %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"ui_button" %>
  </div>
<% end %>

app/views/thrs/_item.html.erb
<div class="thr <%= 'last' if @thrs && @thrs.last == thr %>">
  <% if local_assigns[:show_fav] %>
    <div class="favorite left">
      <div class="fav active"></div>
      <div class="fav_count"><%= thr.users_fav.count if thr.users_fav.count > 0 %></div>
    </div>
  <% end %>
  <div class="thr_marks">
    <div class="thr_mark">
      <div class="thr_votes"><%= thr.vote_count %></div>
      <div class="thr_subtitle"><%= t(:votes) %></div>
    </div>
  <% cache("thrs/#{thr.id}/ans_resolved_and_counter") do %>
    <div class="an_mark <%= "resolved" if thr.resolved? %>">
        <div class="an_count"><%= thr.ans.active.count(:id) %></div>
        <div class="an_subtitle"><%= t("activerecord.models.ans") %></div>
    </div>
  <% end %>
    <div class="clear"></div>
  </div>
  <div class="sneak">
    <h2 class="left">
      <% cache("thrs/#{thr.id}/thr_stitle") do %>
        <%= link_to thr.stitle, thr %>
      <% end %>
    </h2>
    <div class="hits"><%= thr.hits %> <span class="small_font"><%= t(:views) %></span></div>
    <div class="clear"></div>
    <div class="tags">
      <% cache("thrs/#{thr.id}/thr_tags") do %>
        <% thr.tagnames.split(' ').each do |name| %>
          <%= tag_schema(name) %>
        <% end %>
      <% end %>
    </div>
    <div class="authoring">
      <div class="author"><%= user_label_small(thr.last_activity_user) %></div>
      <div class="created_at small_font"><%= distance_of_time_in_words_to_now(thr.activity_at) %></div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</div>

app/views/thrs/_list.html.erb
<% @thrs.each do |thr| %>
    <%= render :partial=> 'thrs/item',:locals => {:thr=>thr} %>
<% end %>

app/views/thrs/_schema.html.erb
<div id="thr" class="lcontent">
  <div id="thr-<%= @thr.id %>">
    <div class="title">
      <h1><%= title @thr.stitle %></h1>
    </div>
    <div class="left_side">
      <%= render :partial=> 'shared/vote', :locals => { :object => @thr }  %>
      <% if current_user  %>
        <div class="favorite">
          <%= link_to '',fav_thr_url(:id=>@thr),:title=>'Dodaj do ulubionych',:class=> (current_user.favs.map(&:activityable).include?(@thr) ? "fav active" : "fav") %>
          <div class="fav_count"><%= @thr.users_fav.count if @thr.users_fav.count > 0 %></div>
        </div>
      <% end %>
    </div>
    <div class="wrap_content right">
        <% if current_user %>
          <div class="content_options">
            <% if can? :report_flag, @thr %>
              <%= link_to t(:report_abuse) ,report_flag_thr_url(@thr.id),:class=>'_flash' %>
              <span class="<%= @thr.class.name.downcase %>_flagged"><%= "(#{@thr.activities.flagged.count})" if @thr.activities.flagged.count > 0 %></span> |
            <% end %>

            <% if can? :report_close,@thr %>
              <% if @thr.closed? %>
                <%= link_to t(:open), reopen_thr_url(@thr.id), :method=> :put %> |
              <% else %>
                <%= link_to t(:close), report_close_thr_url(@thr.id),:class=> '_flash' %>
                <span class="<%= @thr.class.name.downcase %>_closed"><%= "(#{@thr.activities.close_reported.count})" if @thr.activities.close_reported.count > 0 %></span> |
              <% end %>
            <% end %>

            <% if can?(:retag, @thr) && cannot?(:edit, @thr) %>
                <%= link_to (t :retag) , edit_thr_path(@thr.id) %> |
            <% end %>

            <% if can?(:edit, @thr) %>
              <%= link_to (t :edit) , edit_thr_path(@thr.id) %>
            <% end %>

            <% if can?(:destroy, @thr) && !@thr.mark_as_destroyed? %>
                | <%= link_to (t :destroy) , @thr,:class=> '_confirm-remote-delete',"data-confirmation" => 'Czy chcesz usunąć to pytanie ?' %>
            <% end %>
          </div>
        <% end %>
        <div class="thr_content">
          <% cache("thrs/#{@thr.id}/thr_content") do %>
            <%=simple_format h(@thr.content) %>
          <% end %>
        </div>
        <div class="content_bottom">
          <div class="left">
            <div class="tags">
              <% cache("thrs/#{@thr.id}/thr_tags") do %>
                <% @thr.tagnames.split(' ').each do |name| %>
                  <%= tag_schema(name) %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="right margin_left">
            <div class="created_at small_font"><%= t(:created) %> <%= distance_of_time_in_words_to_now(@thr.created_at) %></div>
            <div class="author"><%= user_label(@thr.user) %></div>
          </div>
          <% if @thr.versions.count > 0 %>
            <div class="right">
              <div class="created_at small_font"><%= link_to "#{t(:edited)} #{distance_of_time_in_words_to_now(@thr.versions.last.created_at)}",history_thr_url(@thr) %></div>
              <div class="author"><%= user_label(@thr.versions.last.user) unless @thr.versions.last.user_id == @thr.user_id %></div>
            </div>
          <% end %>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <div id="thr-<%= @thr.id %>" class="comments">
          <% @comments = @thr.comments.active.sortable %>
          <%= render :partial=>'comments/list' %>
          <% if can? :new, @thr.comments.build %>
            <div class="light_sep"></div>
            <div class="new_comment_a" >
              <%= link_to t("comments.new.comment_thr"),new_thr_comment_url(:thr_id=>@thr.id),:id=>'add_comment',:class=> 'ui_button small' %>
            </div>
            <div class="new_comment"></div>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
    <% if @thr.closed? %>
      <% close_activity = @thr.activities.close_reported.last %>
      <h2><%=raw t('thrs.closed.summary',:user=>close_activity.user.sname,:reason=>close_activity.extra) %></h2>
    <% end %>
  </div>  
  <div class="answers">
    <% if @ans.count > 0 %>
      <div class="title">
        <h2 class="left"><%= @ans.count %> <%= t("activerecord.models.ans") %></h2>
        <div class="right">
          <%= render_navigation(:context=>:ans_sort) %>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>
    <%= render 'ans/list' %>
  </div>
</div>

app/views/thrs/_shortlist.html.erb
<% @thrs.each do |thr| %>
    <div class="thr <%= 'last' if @thrs.last == thr %>">
      <div class="left">
        <div class="votes"><%= thr.vote_count %></div>
        <div class="thr_subtitle"><%= t(:votes) %></div>
      </div>
      <div class="left <%= "resolved" if thr.resolved? %>">
        <div class="votes"><%= thr.ans.count %></div>
        <div class="thr_subtitle"><%= t("activerecord.models.ans") %></div>
      </div>
      <div class="left" style="margin-left:5px;">
        <h2><%= link_to thr.stitle, thr %></h2>
        <div>
          <div class="tags">
            <% thr.tags.each do |t| %>
              <%= link_to t.name,tag_path(t) %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="right">
        <div class="hits"><%= thr.hits %> <span class="small_font"><%= t(:views) %></span></div>
        <div class="author"><%= user_label_small(thr.last_activity_user) %></div>
        <div class="created_at small_font"><%= distance_of_time_in_words_to_now(thr.activity_at) %></div>
      </div>
      <div class="clear"></div>
    </div>
<% end %>

app/views/thrs/_subscription.html.erb
<% if current_user %>
  <% unless @subscribe %>
    <%= t('thrs.unsubscribe.desc') %>
    <div style="margin:5px;"><%= link_to t('thrs.subscribe.link'),subscribe_thr_url(@thr.id),:class=> 'remote-update ui_button small'  %></div>
  <% else %>
    <%= t('thrs.subscribe.desc') %>
    <div style="margin:5px;"><%= link_to t('thrs.unsubscribe.link'),subscribe_thr_url(@thr.id),:class=> 'remote-update ui_button small'  %></div>
  <% end %>
<% end %>

app/views/thrs/edit.html.erb
<div class="lcontent">
  <div class="title">
    <h2><%= title "#{t(:edit)} #{@thr.stitle}" %></h2>
  </div>
  <div class="icontent">
    <%= render 'form_retag' if can?(:retag, @thr) && cannot?(:edit, @thr) %>
    <%= render 'form' if can?(:edit, @thr) %>
  </div>
</div>
<div class="rhelper">
  <% if can?(:edit, @thr) %>
    <div class="block">
      <div class="title"><h3><%= t "thrs.edit.when_title" %></h3></div>
      <div class="bdesc"><%= t "thrs.edit.when_content" %></div>
    </div>
  <% end %>

  <% if can?(:retag, @thr) && can?(:edit, @thr) %>
    <div class="block">
      <div class="title"><h3><%= t("activerecord.models.tags") %></h3></div>
      <div class="bdesc"><%= t "thrs.edit.tag_content", :min=> Tag::MIN_TAGS, :max=> Tag::MAX_TAGS %></div>
    </div>
  <% end %>

  <% if can?(:edit, @thr) %>
    <div class="block">
      <div class="title"><h3><%= t "thrs.edit.version_and_note_title" %></h3></div>
      <div class="bdesc"><%= t "thrs.edit.version_and_note_content" %></div>
    </div>
  <% end %>
</div>
<div class="clear"></div>

app/views/thrs/fav.js.erb
$('#<%= @thr.class.name.downcase %> .favorite').html('<%= escape_javascript( 
  link_to '',fav_thr_url(:id=>@thr),:class=> (current_user.favs.map(&:activityable).include?(@thr) ? "fav active" : "fav")
) %><div class="fav_count"><%= @thr.users_fav.count if @thr.users_fav.count > 0 %></div>');

app/views/thrs/flag.js.erb
$('.content_options .thr_flagged').html('(<%= @thr.activities.flagged.count %>)')
delay_flash_window_close('dziekujemy za zgloszenie')

app/views/thrs/history.html.erb
<%= render :partial=> 'shared/history',:locals=> {:object => @thr} %>

app/views/thrs/index.html.erb
<%= render :partial=>'main/thrs' %>

app/views/thrs/new.html.erb
<div class="lcontent">
  <div class="title">
    <h1><%= title(t('thrs.new.title')) %></h1>
  </div>
  <div class="icontent"><%= render 'form' %></div>
  
</div>
<div class="rhelper">
  <div class="block">
    <div class="title"><h3>Create new question only when:</h3></div>
    <div class="bdesc">
      <ul>
        <li>you can't find it on this website</li>
        <li>you found a bug or have suggestion to improve this website</li>
      </ul>
    </div>
  </div>

  <div class="block">
    <div class="title"><h3>Tags</h3></div>
    <div class="bdesc">
      Add from <%= Tag::MIN_TAGS %> to <%= Tag::MAX_TAGS %> keywords separated by a space, that will allow others find your question
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/thrs/show.html.erb
<%= render 'thrs/schema' %>
<div class="rhelper">
  <div class="block">
    <div class="title"><h3><%= t("thrs.show.details") %></h3></div>
    <div class="tags">
      <% @tag_thr.each do |k,v| %>
          <%= tag_schema(k,v) %>
      <% end %>
    </div>
    <div class="bdesc">
      <div><%= t(:created) %>: <%= l @thr.created_at,:format=>:short %></div>
      <div><%= t(:views) %>: <%= @thr.hits %></div>
      <% if @thr.versions.count > 0 %>
        <div><%= t(:edit) %>: <%= l @thr.versions.last.created_at,:format=>:short %></div>
      <% end %>
    </div>
  </div>
  <% if current_user %>
    <%#*<div class="block">%>
      <%#*<div class="title"><h3>Share question</h3></div>%>
      <%#*<div class="bdesc">%>
        <%#= render :partial=> 'shared/shareit', :locals => { :object => @thr }  %>
      <%#*</div>%>
    <%#*</div>%>
    <div class="block">
      <div class="title"><h3><%= t("thrs.show.interesting") %></h3></div>
      <div class="bdesc">
        <div class="thr_sub">
          <%= render :partial=> 'thrs/subscription' %>
        </div>
      </div>
    </div>
  <% end %>
  <% cache("thrs/#{@thr.id}/related_thrs") do %>
    <% if !@related_thrs.blank? %>
      <div class="block">
        <div class="title"><h3><%= t("thrs.show.related") %></h3></div>
        <% @related_thrs.each do |thr| %>
          <div class="related"><%= link_to thr.stitle,thr %></div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  
</div>
<div class="clear"></div>

app/views/thrs/show.js.erb
<%= render 'schema' %>