config/routes.rb
Qaror::Application.routes.draw do

  resources :pages

  #
  # admin
  #
  namespace :admin do
    root :to => "main#index"
    resources :main do
      collection do
        get 'thrs'
        get 'ans'
        get 'comments'
      end
    end
    resources :activities do
      collection do
        get 'reported'
      end
    end
    resources :pages
    resources :stats
    resources :badges
    resources :users
    resources :contact_us
  end

  match '/auth/:provider/callback' => 'login#create'
  match '/auth/failure' => 'login#failure'

  resources :search do
    collection do
      get 'tags'
    end
  end

  resources :achievements, :path => "/achievements"

  resources :comments
  match '/comments/:id/vote/:vote',:to=>'comments#vote', :as => :vote_comments

  resources :tags
  match '/tags/sort/:sort', :to => 'tags#index', :as => :tags_sort
  match '/tags/:id/:sort', :to => 'tags#show', :as => :tag_sort

  resources :ans, :path => "/answers" do
    resources :comments

    member do
      put 'edit'
      get 'report_flag'
      put 'flag'
      get 'history'
    end
  end

  match '/answers/:id/resolved' => 'ans#resolved', :as => :resolved_an
  match '/answers/:id/unresolved' => 'ans#unresolved', :as => :unresolved_an
  match '/answers/:id/vote/:vote',:to=>'ans#vote', :as => :vote_ans

  match '/questions/:id/sort/:sort',:to=>'thrs#show', :as => :ans_sort


  resources :thrs, :path => "/questions" do
    resources :comments
    member do
      put 'edit'
      get 'fav'
      get 'report_close'
      get 'report_flag'
      post 'answer'
      put 'close'
      put 'flag'
      put 'reopen'
      put 'subscribe'
      get 'history'
    end
  end
  match '/questions/:id/vote/:vote',:to=>'thrs#vote', :as => :vote_thrs
  match '/questions/sort/:sort', :to => 'thrs#index', :as => :thrs_sort

  resources :login

  match '/users/profile', :to=> 'users#update', :via => :put
  match '/users/profile', :to=> 'users#edit', :via => :get, :as=>:profile
  resources :users, :path => "/users" do
    collection do
      get 'activate'
      get 'remind_password_edit'
      post 'remind_password'
      get 'change_password'
      post 'change_password'
      get 'ako'
    end
    member do
      get 'send_activation_link'
      get 'activity'
      get 'reputation'
      get 'votes'
      get 'favorites'
    end
  end

  match '/contact' => 'main#pages', :as => :contact_us
  match '/faq' => 'main#pages', :as => :faq
  match '/privacy' => 'main#pages', :as => :privacy
  match '/privileges' => 'pages#privileges', :as => :privileges
  
  match '/remind_password', :to => 'users#remind_password_edit',:as=>:remind_password
  match '/register', :to => 'users#new',:as => :register
  match '/login', :to => 'login#index',:as => :login
  match '/logout', :to => 'login#logout',:as => :logout
#  match '/wp', :to=> 'main#wiki_parser', :as=>:wiki_parser
  root :to => 'thrs#index'

end

app/controllers/admin/users_controller.rb
module Admin

  class UsersController < ApplicationController

    layout "admin"
    before_filter :verify_admin

    # GET /users
    # GET /users.xml
    def index
      @users = User.order("created_at ASC")

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
      end
    end

    # GET /users/1
    # GET /users/1.xml
    def show
      @user = User.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    end

    # GET /users/new
    # GET /users/new.xml
    def new
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @user }
      end
    end

    # GET /users/1/edit
    def edit
      @user = User.find(params[:id])
    end

    # POST /users
    # POST /users.xml
    def create
      @user = User.new
      @user.accessible = :all if current_user.is_admin?
      @user.name = params[:user][:name]
      @user.email = params[:user][:email]
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation] # in mass assigment this not pass
#      @user.activation_hash = Digest::SHA512.hexdigest(Time.zone.now.to_s)
      @user.role = User::ROLE_USER
      @user.status = (params[:user][:status] && params[:user][:status].to_i == 2) ? User::STATUS_ACTIVE : User::STATUS_NOTCONFIRMED

      respond_to do |format|
        if @user.save
          flash[:notice] = t('users.successfully_created') + @user.email
          format.html { redirect_to(user_url(@user), :notice => t(:saved)) }
        else
          format.html { render :action => "new" }
        end
      end
    end

    # PUT /users/1
    # PUT /users/1.xml
    def update
      @user = User.find(params[:id])
      @user.accessible = :all if current_user.is_admin?
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to(edit_admin_user_path(@user), :notice => t(:saved))  }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.xml
    def destroy
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to(admin_users_url) }
        format.xml  { head :ok }
      end
    end

    def block
      @user = User.find(params[:id])
      @user.block
    end

    def refresh_messages_size
      user = User.find(params[:id])
      user.import_messages.each do |im|
          if im.importing?
            redirect_to(edit_admin_user_path(user), :notice => 'Obecnie trwa import. Sprobuj za chwile')
            return
          end
      end
      user.refresh_messages_size
      redirect_to(edit_admin_user_path(user))
      return
    end

    def refresh_attaches_size
      user = User.find(params[:id])
      user.refresh_attaches_size
      redirect_to(edit_admin_user_path(user))
      return
    end

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  authorize_resource :class => false

  # GET /users
  # GET /users.xml
  def index
    @users = User.active.sortable(params[:sort]).
      paginate(:per_page=>24,:page=>params[:page])


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.active.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation] # in mass assigment this not pass
    @user.activation_hash = Digest::SHA512.hexdigest(Time.zone.now.to_s)
    @user.role = User::ROLE_USER
    @user.status = User::STATUS_NOTCONFIRMED

    @user.captcha = params[:user][:captcha]
    @user.captcha_key = params[:user][:captcha_key]

    respond_to do |format|
      if @user.save_with_captcha
        m = Mailer.registration_confirmation(@user).deliver
        flash[:notice] = t('users.successfully_created') + @user.email
        format.html { login_user_and_redirect(@user,@user) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user

    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.birth = Date.civil(params[:user][:"birth(1i)"].to_i,params[:user][:"birth(2i)"].to_i,params[:user][:"birth(3i)"].to_i)
#    @user.birth = params[:user][:birth]
    @user.www = params[:user][:www]
    @user.about = params[:user][:about]

    @user.user_setting.update_attributes(params[:user_setting])
    Extender::Activities.update_user(@user)
    respond_to do |format|
      if @user.save
        flash[:notice] = t :saved
        format.html { redirect_to(edit_user_url) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  # GET /users/remind_password_create
  def remind_password_edit
    @user = User.new
  end

# POST /users/remind_password
  def remind_password
    @user = User.active.where(:email=>params[:user][:email]).first
    
    if @user.nil?
      flash[:user_error] = t 'users.email_not_exists_or_blocked'
      render :action => "remind_password_edit"
      return
    else
      @user.remind_token = SecureRandom.hex(18)
      @user.captcha = params[:user][:captcha]
      @user.captcha_key = params[:user][:captcha_key]
    end
    
    respond_to do |format|
      if @user.save_with_captcha
        Mailer.remind_password(@user).deliver
        flash[:notice] = t 'users.remind_password_send'
        format.html { redirect_to root_url }
      else
        format.html { render :action => "remind_password_edit" }
      end
    end
  end

  # POST /users/change_password
  def change_password
    # check hash
    @user = User.active.where(:remind_token=>params[:hash]).first
    if @user.nil?
      redirect_to root_url
      return
    end
    respond_to do |format|
      if request.post?
          @user.password = params[:user][:password]
          @user.password_confirmation = params[:user][:password_confirmation]
          @user.updating_password = true
          if @user.save
            @user.updating_password = false
            @user.remind_token = nil
            if @user.not_confirmed? # if user not active? or block?
              @user.activation_hash = nil
              @user.status = User::STATUS_ACTIVE
            end
            @user.save
            flash[:notice] = t "users.remind_password_confirm"
            format.html { redirect_to root_url }
          else
            format.html
          end
      else
        format.html
      end
    end
  end

  # GET /users/activate
  def activate
    @user = User.where(:activation_hash=>params[:hash],:status=> User::STATUS_NOTCONFIRMED).first
    respond_to do |format|
      unless @user.nil?
        @user.activation_hash = nil
        @user.status = User::STATUS_ACTIVE
        @user.save
        Extender::Activities.confirm_email(@user)
        flash[:notice] = t :user_successfully_activated
        format.html { redirect_to root_url}
      else
        format.html { redirect_to root_url}
      end
    end
  end

  def send_activation_link
    @user = User.where(:status=>User::STATUS_NOTCONFIRMED).find(params[:id])
    @user.activation_hash = Digest::SHA512.hexdigest(Time.zone.now.to_s)

    respond_to do |format|
      if @user.save
        m = Mailer.registration_confirmation(@user).deliver
        flash[:notice] = 'Wyslano link aktywacyjny'
        format.html { redirect_to :action => "edit" }
#        format.js { render_flash_window :content => 'Wyslano link aktywacyjny'}
      end
    end
  end

  def ako
    # params[:k] - api key
    # params[:opt] - option / unckeck all subscribed field / uncheck question only
    # params[:opt_id] - option id
    @user = User.active.find_by_apikey!(params[:k])
    if params[:opt] == 'sub_q' && params[:opt_id] # users/ako?k=da42j..34jnk&opt=sub_q&opt_id=11
      @thr = Thr.find(params[:opt_id])
      @thr.subscribe(@user.id) if @thr.subscribed?(@user.id)
      flash[:notice] = t "users.subscription.uncheck_thr"
      redirect_to @thr
    elsif params[:opt] == 'sub_a'
      @user.user_setting.uncheck_all_notifies
      flash[:notice] = t "users.subscription.uncheck_all"
      redirect_to @user
    else
      response_404
    end
  end

  def activity
    @user = User.active.find(params[:id])
  end

  def reputation
    @user = User.active.find(params[:id])
  end

  def votes
    @user = User.active.find(params[:id])
  end

  def favorites
    @user = User.active.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def role(integer)
    case integer
      when User::ROLE_NONE then 'nieaktywny'
      when User::ROLE_USER then 'uzytkownik'
      when User::ROLE_MODERATOR then 'moderator'
      when User::ROLE_ADMIN then 'admin'
    end
  end

  def status(integer)
    case integer
      when User::STATUS_ANONYMOUS then 'anonim'
      when User::STATUS_NOTCONFIRMED then 'niepotwierdzony'
      when User::STATUS_ACTIVE then 'aktywny'
      when User::STATUS_BLOCKED then 'zablokowany'
    end
  end

  def user_label(user)
    @user = user
    render :partial=>'users/user_label'
  end

  def user_label_small(user)
    @user = user
    render :partial=>'users/user_label',:locals=>{:small=>true}
  end

  def reputation_sign_humanized(value)
    return "plus" if value > 0
    return "minus" if value < 0
    return "zero" if value == 0
  end

  def reputation_sign(value)
    return "+" if value > 0
    return "" if value <= 0
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<div class="row show-grid">
  <div class="col-md-3">
    <div id="avatars">
      <div id="gravatar">
        <%= image_tag(APP_CONFIG['gravatar_url'] + Digest::MD5.hexdigest(@user.email) + "?d=identicon&s=125") %>
        <div><%= link_to t('users.change_gravatar'),"http://pl.gravatar.com/" %></div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= link_to t('users.activation_link'),send_activation_link_user_url(@user) if @user.not_confirmed? %>
    </div>
    <div class="field">
      <%= f.label :birth %>
      <%= f.date_select :birth, :start_year => Date.current.year, :end_year => 1920 %>
    </div>
    <div class="field">
      <%= f.label :www %>
      <%= f.text_field :www %>
    </div>
  </div>
  <div class="col-md-5">
    <div class="field">
      <%= f.label :about %>
      <%= f.text_area :about,:size=>'50x15' %>
    </div>
  </div>
  <div class="field" style="float:right;width:421px;margin-right:18px;">
    <%= field_messages_for @user %>
  </div>
  <div class="clear"></div>
  <div>
    <div class="title">
      <h2><%=t 'users.subscription.title' %></h2>
    </div>
    <strong><%=t 'users.subscription.desc' %>:</strong>
    <div>
      <%= hidden_field_tag 'user_setting[notify_answers]',0 %>
      <%= check_box_tag 'user_setting[notify_answers]',1, @user.user_setting.notify_answers==1 %>
      <%= f.label t('users.subscription.notify_answers') %>
    </div>
    <div>
      <%= hidden_field_tag 'user_setting[notify_comments]',0 %>
      <%= check_box_tag 'user_setting[notify_comments]',1, @user.user_setting.notify_comments==1 %>
      <%= f.label t('users.subscription.notify_comments') %>
    </div>
    <div>
      <%= hidden_field_tag 'user_setting[notify_answer_resolved]',0 %>
      <%= check_box_tag 'user_setting[notify_answer_resolved]',1, @user.user_setting.notify_answer_resolved==1 %>
      <%= f.label t('users.subscription.notify_answer_resolved') %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit t(:save), :class=> 'ui_button' %>
  </div>
</div>
<% end %>

app/views/users/_list.html.erb
<% @users.each do |user| %>
  <%= user_label(user) %>
<% end %>

app/views/users/_user_label.html.erb
<% if local_assigns[:small].nil? %>
  <div class="user_l">
    <%= image_tag(APP_CONFIG['gravatar_url'] + Digest::MD5.hexdigest(@user.email) + "?d=identicon&s=40",
      :class=> 'left',:width=>'40px',:height=>'40px') %>
    <div class="name"><%= link_to raw(@user.sname),@user %></div>
    <span class="reputation"><%= @user.reputation %></span>
    <%= render 'users/user_ranks' %>
    <div class="clear"></div>
  </div>
<% else %>
  <div class="user_ls">
    <div class="name"><%= link_to raw(@user.sname),@user %></div>
    <span class="reputation"><%= link_to @user.reputation, votes_user_path(@user) %></span>
  </div>
<% end %>

app/views/users/_user_ranks.html.erb
<div class="ranks">
  <% if !@user.ranks.blank? %>
    <%=raw "<span class=\"gold\">#{@user.ranks["gold"]}</span>" if @user.ranks["gold"] %>
    <%=raw "<span class=\"silver\">#{@user.ranks["silver"]}</span>" if @user.ranks["silver"] %>
    <%=raw "<span class=\"bronze\">#{@user.ranks["bronze"]}</span>" if @user.ranks["bronze"] %>
  <% end %>
</div>

app/views/users/_user_stuff.html.erb
<div class="user_stuff">
  <% unless current_user %>
      <%= link_to t(:login), login_url, :class=>'ui_button' %>
      <%= link_to t('users.new'), register_url,:class=>'ui_button' %>
  <% else %>
      <%= user_label_small(current_user) %>
      <%= link_to t(:profile), profile_url, :class=>'ui_button' %>
      <%= link_to t(:logout), logout_url, :class=>'ui_button notsoimportant' %>
  <% end %>
</div>

app/views/users/activity.html.erb
<div class="title">
  <h2 class="left"><%=raw @user.sname %></h2>
  <div class="right">
    <%= render_navigation(:context=>:user_tabs) %>
  </div>
  <div class="clear"></div>
</div>
<div class="summary">
  <em><%= @user.activities.public_activities.count %></em>
  <%=t 'sort.user_tabs.activity' %>
</div>
<div id="content">
  <table>
    <% @user.activities.public_activities.order("created_at desc").each do |activity| %>
      <tr>
        <td><h2 class="grey_font"><%= distance_of_time_in_words_to_now(activity.created_at) %></h2></td>
        <td><%= activity.name_humanized %></td>
        <td>
            <% if activity.activityable_type == 'Thr' %>
              <strong><%= link_to activity.activityable.stitle, thr_url(activity.activityable.id) %></strong>
            <% elsif activity.activityable_type == 'An' %>
              <strong><%= link_to activity.activityable.thr.stitle, thr_url(activity.activityable.thr.id,:anchor=> 'an-'+activity.activityable.id.to_s) %></strong>
            <% elsif activity.activityable_type == 'Comment' %>
              <strong><%= activity.activityable.content %></strong>
            <% elsif activity.achievement %>
              <%= achievement_schema(activity.achievement.badge) %>
              <% activity.activityable.stitle if activity.activityable %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/change_password.html.erb
<div id="tight">
  <div class="title">
    <h2><%= t 'users.change_password' %></h2>
  </div>
  <div class="content">
    <div class="desc"><%= t 'users.change_password_desc' %></div>
    <%= form_for :user, :url => request.url do |f| %>
      <div class="field">
        <%= f.label t 'activerecord.attributes.user.password' %>
        <%= f.password_field :password,:value=>nil %>
      </div>
      <div class="field">
        <%= f.label t 'activerecord.attributes.user.password_confirmation' %>
        <%= f.password_field :password_confirmation,:value=>nil %>
      </div>
      <div class="field">
        <%= field_messages_for(@user) %>
      </div>
      <div class="actions">
        <%= submit_tag (t :save),:class=>"ui_button" %>
      </div>
    <% end %>
  </div>
</div>  
<div class="clear"></div>

app/views/users/edit.html.erb
<div class="title">
  <h2><%= t 'users.edit.title' %> <%=raw @user.sname %></h2>
</div>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="title">
  <h1 class="left"><%= title t('activerecord.models.users') %></h1>
  <div class="right">
    <%= render_navigation(:context=>:users_sort) %>
  </div>
  <div class="clear"></div>
</div>
<div id="users" class="icontent">
  <%= render 'list'  %>
</div>
<%= will_paginate(@users,:params => { :format => nil }) %>

app/views/users/new.html.erb
<div id="tight">
  <div class="title">
    <h1><%= title t("users.new") %></h1>
  </div>
  <div class="content">
    <%= form_for(@user) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %> &nbsp;
        <span style="height:26px;line-height:26px;" class="small_font"> (<%= t("users.email_not_public") %>)</span>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="field">
        <%= f.simple_captcha %>
      </div>
      <div class="field">
        <%= t"users.agreement_note",:button=>t("users.new") %> <strong><%= link_to t('users.agreement_link'), privacy_url,:target=> '_blank' %></strong>
      </div>
      <div class="field">
        <%= field_messages_for @user %>
      </div>
      <div class="actions">
        <%= f.submit t("users.new"), :class=>"ui_button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/remind_password_edit.html.erb
<div id="tight">
  <div class="title">
    <h1><%= t 'users.remind_password_question' %></h1>
  </div>
  <div class="content">
    <div class="desc"><%= t 'users.remind_password_desc' %></div>
    <%= form_for :user, :url => { :action => "remind_password" } do |f| %>
      <div class="field">
        <%= f.label t('activerecord.attributes.user.email') %>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.simple_captcha %>
      </div>
      <div class="field">
        <% if @user %>
          <%= field_messages_for(@user) %>
        <% else %>
          <%= flash_form_messages(:user) %>
        <% end %>
      </div>
      <div class="actions">
        <%= submit_tag t('users.send_to_email'),:class=>"ui_button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/reputation.html.erb
<div class="title">
  <h2 class="left"><%=raw @user.sname %></h2>
  <div class="right">
    <%= render_navigation(:context=>:user_tabs) %>
  </div>
  <div class="clear"></div>
</div>
<div class="summary">
  <em><%= @user.reputation %></em>
  <%=t 'sort.user_tabs.reputation' %>
</div>
<div id="content">
  <table>
    <% @user.reputation_points.each do |activity_point| %>
      <tr>
        <td>
          <% avalue = activity_point.value %>
          <div class="<%= reputation_sign_humanized(avalue) %>"><%= reputation_sign(avalue) %><%= avalue %></div>
        </td>
        <td><div class="grey_font"><%= distance_of_time_in_words_to_now(activity_point.created_at) %></div></td>
        <td><%= activity_point.activity.name_humanized %></td>
        <td><strong>
            <% if activity_point.activity.activityable_type == 'Thr' %>
              <%= activity_point.activity.activityable.title %>
            <% elsif activity_point.activity.activityable_type == 'An' %>
              <%= activity_point.activity.activityable.thr.stitle %>
            <% elsif activity_point.activity.activityable_type == 'Comment' %>
              <%= activity_point.activity.activityable.content %>
            <% elsif activity_point.activity.achievement %>
              <%= activity_point.activity.achievement.name_or_tag %>
            <% end %>
          </strong>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="title">
  <h2 class="left"><%=raw title(@user.sname) %></h2>
  <div class="right">
    <%= render_navigation(:context=>:user_tabs) %>
  </div>
  <div class="clear"></div>
</div>
<div class="row show-grid">
  <div class="col-md-3">
    <div id="avatars">
      <div id="gravatar">
        <%= image_tag(APP_CONFIG['gravatar_url'] + Digest::MD5.hexdigest(@user.email) + "?d=identicon&s=128") %>
      </div>
    </div>
    <div class="user_reputation"><%= @user.reputation %></div>
  </div>
  <div class="col-md-4">
    <div class="field">
      <div class="flabel"><%= t('activerecord.attributes.user.name2') %></div>
      <div class="fdesc"><%=raw @user.sname %></div>
    </div>
    <div class="field">
      <div class="flabel"><%= t('activerecord.attributes.user.created_at') %></div>
      <div class="fdesc"><%= distance_of_time_in_words_to_now(@user.created_at) %></div>
    </div>
    <div class="field">
      <div class="flabel"><%= t('activerecord.attributes.user.last_login') %></div>
      <div class="fdesc"><%= distance_of_time_in_words_to_now(@user.last_login) %></div>
    </div>
    <div class="field">
      <div class="flabel"><%= t('activerecord.attributes.user.age') %></div>
      <div class="fdesc"><%= "#{(Time.now.year - @user.birth.year)} lat" if @user.birth %></div>
    </div>
    <div class="field">
      <div class="flabel">www:</div>
      <div class="fdesc"><%= @user.www %></div>
    </div>
  </div>
  <div class="col-md-5">
      <div style="min-height:250px;background-color:#ddd;padding:5px;">
        <% if @user.about %>
          <%=raw @user.about.gsub(/\n/, '<br/>') %>
        <% else %>
          (<%=raw @user.sname %>`s bio is blank)
        <% end %>
      </div>
  </div>
</div>
<div class="row show-grid">
  <div class="col-md-8">
    <div class="title">
      <h2 class="summary"><em><%= @user.thrs.count %></em><%= t "users.show.questions" %></h2>
    </div>
    <div class="content small" id="thrs">
      <% @thrs = @user.thrs %>
      <%= render 'thrs/list' %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="title">
      <h2 class="summary"><em><%= @user.ans.count %></em><%= t "users.show.answers" %></h2>
    </div>
    <div class="content" id="ans">
      <% @user.ans.each do |an| %>
        <div class="an">
          <h3>
            <%= link_to raw("<span class=\"an_votes #{"resolved" if an.resolved?}\">#{an.vote_count}</span>"),an.thr %>
            <%= link_to an.thr.stitle,an.thr %>
          </h3>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row show-grid">
  <div class="col-md-6">
    <div class="title">
      <h2 class="summary"><em><%= @user.votes.count %></em><%= t "users.show.votes" %></h2>
    </div>
    Up votes: <%= @user.votes_up.count %>
    Down votes: <%= @user.votes_down.count %>
  </div>
  <div class="col-md-6">
    <div class="title">
      <h2 class="summary"><em><%= @user.tags.count %></em><%= t "users.show.tags" %></h2>
    </div>
    <div class="tags">
      <% @user.tags.each do |tag| %>
        <%= tag_schema tag.name,tag.quantity %>
      <% end %>
    </div>
  </div>
</div>
<div class="title">
  <h2 class="summary"><em><%= @user.badges.count %></em><%= t "users.show.achievements" %></h2>
</div>
<div class="achievements">
<% @user.badges.each do |badge| %>
  <%= achievement_schema(badge) %>
<% end %>
</div>

app/views/users/votes.html.erb
<div class="title">
  <h2 class="left"><%=raw @user.sname %></h2>
  <div class="right">
    <%= render_navigation(:context=>:user_tabs) %>
  </div>
  <div class="clear"></div>
</div>
<div id="content">
  <table id="activity_table">
    <% @user.reputation_points.each do |activity_point| %>
      <tr>
        <td>
          <% avalue = activity_point.value %>
          <div class="<%= reputation_sign_humanized(avalue) %>"><%= reputation_sign(avalue) %><%= avalue %></div>
        </td>
        <td><div class="grey_font"><%= distance_of_time_in_words_to_now(activity_point.created_at) %></div></td>
        <td><%= activity_point.activity.name_humanized %></td>
        <td><strong>
            <% if activity_point.activity.activityable_type == 'Thr' %>
              <%= activity_point.activity.activityable.title %>
            <% elsif activity_point.activity.activityable_type == 'An' %>
              <%= activity_point.activity.activityable.thr.stitle %>
            <% elsif activity_point.activity.activityable_type == 'Comment' %>
              <%= activity_point.activity.activityable.content %>
            <% elsif activity_point.activity.achievement %>
              <%= activity_point.activity.achievement.name_or_tag %>
            <% end %>
          </strong>
        </td>
      </tr>
    <% end %>
  </table>
</div>