config/routes.rb
Qaror::Application.routes.draw do

  resources :pages

  #
  # admin
  #
  namespace :admin do
    root :to => "main#index"
    resources :main do
      collection do
        get 'thrs'
        get 'ans'
        get 'comments'
      end
    end
    resources :activities do
      collection do
        get 'reported'
      end
    end
    resources :pages
    resources :stats
    resources :badges
    resources :users
    resources :contact_us
  end

  match '/auth/:provider/callback' => 'login#create'
  match '/auth/failure' => 'login#failure'

  resources :search do
    collection do
      get 'tags'
    end
  end

  resources :achievements, :path => "/achievements"

  resources :comments
  match '/comments/:id/vote/:vote',:to=>'comments#vote', :as => :vote_comments

  resources :tags
  match '/tags/sort/:sort', :to => 'tags#index', :as => :tags_sort
  match '/tags/:id/:sort', :to => 'tags#show', :as => :tag_sort

  resources :ans, :path => "/answers" do
    resources :comments

    member do
      put 'edit'
      get 'report_flag'
      put 'flag'
      get 'history'
    end
  end

  match '/answers/:id/resolved' => 'ans#resolved', :as => :resolved_an
  match '/answers/:id/unresolved' => 'ans#unresolved', :as => :unresolved_an
  match '/answers/:id/vote/:vote',:to=>'ans#vote', :as => :vote_ans

  match '/questions/:id/sort/:sort',:to=>'thrs#show', :as => :ans_sort


  resources :thrs, :path => "/questions" do
    resources :comments
    member do
      put 'edit'
      get 'fav'
      get 'report_close'
      get 'report_flag'
      post 'answer'
      put 'close'
      put 'flag'
      put 'reopen'
      put 'subscribe'
      get 'history'
    end
  end
  match '/questions/:id/vote/:vote',:to=>'thrs#vote', :as => :vote_thrs
  match '/questions/sort/:sort', :to => 'thrs#index', :as => :thrs_sort

  resources :login

  match '/users/profile', :to=> 'users#update', :via => :put
  match '/users/profile', :to=> 'users#edit', :via => :get, :as=>:profile
  resources :users, :path => "/users" do
    collection do
      get 'activate'
      get 'remind_password_edit'
      post 'remind_password'
      get 'change_password'
      post 'change_password'
      get 'ako'
    end
    member do
      get 'send_activation_link'
      get 'activity'
      get 'reputation'
      get 'votes'
      get 'favorites'
    end
  end

  match '/contact' => 'main#pages', :as => :contact_us
  match '/faq' => 'main#pages', :as => :faq
  match '/privacy' => 'main#pages', :as => :privacy
  match '/privileges' => 'pages#privileges', :as => :privileges
  
  match '/remind_password', :to => 'users#remind_password_edit',:as=>:remind_password
  match '/register', :to => 'users#new',:as => :register
  match '/login', :to => 'login#index',:as => :login
  match '/logout', :to => 'login#logout',:as => :logout
#  match '/wp', :to=> 'main#wiki_parser', :as=>:wiki_parser
  root :to => 'thrs#index'

end

app/controllers/admin/users_controller.rb
module Admin

  class UsersController < ApplicationController

    layout "admin"
    before_filter :verify_admin

    # GET /users
    # GET /users.xml
    def index
      @users = User.order("created_at ASC")

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
      end
    end

    # GET /users/1
    # GET /users/1.xml
    def show
      @user = User.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    end

    # GET /users/new
    # GET /users/new.xml
    def new
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @user }
      end
    end

    # GET /users/1/edit
    def edit
      @user = User.find(params[:id])
    end

    # POST /users
    # POST /users.xml
    def create
      @user = User.new
      @user.accessible = :all if current_user.is_admin?
      @user.name = params[:user][:name]
      @user.email = params[:user][:email]
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation] # in mass assigment this not pass
#      @user.activation_hash = Digest::SHA512.hexdigest(Time.zone.now.to_s)
      @user.role = User::ROLE_USER
      @user.status = (params[:user][:status] && params[:user][:status].to_i == 2) ? User::STATUS_ACTIVE : User::STATUS_NOTCONFIRMED

      respond_to do |format|
        if @user.save
          flash[:notice] = t('users.successfully_created') + @user.email
          format.html { redirect_to(user_url(@user), :notice => t(:saved)) }
        else
          format.html { render :action => "new" }
        end
      end
    end

    # PUT /users/1
    # PUT /users/1.xml
    def update
      @user = User.find(params[:id])
      @user.accessible = :all if current_user.is_admin?
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to(edit_admin_user_path(@user), :notice => t(:saved))  }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.xml
    def destroy
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to(admin_users_url) }
        format.xml  { head :ok }
      end
    end

    def block
      @user = User.find(params[:id])
      @user.block
    end

    def refresh_messages_size
      user = User.find(params[:id])
      user.import_messages.each do |im|
          if im.importing?
            redirect_to(edit_admin_user_path(user), :notice => 'Obecnie trwa import. Sprobuj za chwile')
            return
          end
      end
      user.refresh_messages_size
      redirect_to(edit_admin_user_path(user))
      return
    end

    def refresh_attaches_size
      user = User.find(params[:id])
      user.refresh_attaches_size
      redirect_to(edit_admin_user_path(user))
      return
    end

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  authorize_resource :class => false

  # GET /users
  # GET /users.xml
  def index
    @users = User.active.sortable(params[:sort]).
      paginate(:per_page=>24,:page=>params[:page])


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.active.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation] # in mass assigment this not pass
    @user.activation_hash = Digest::SHA512.hexdigest(Time.zone.now.to_s)
    @user.role = User::ROLE_USER
    @user.status = User::STATUS_NOTCONFIRMED

    @user.captcha = params[:user][:captcha]
    @user.captcha_key = params[:user][:captcha_key]

    respond_to do |format|
      if @user.save_with_captcha
        m = Mailer.registration_confirmation(@user).deliver
        flash[:notice] = t('users.successfully_created') + @user.email
        format.html { login_user_and_redirect(@user,@user) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user

    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.birth = Date.civil(params[:user][:"birth(1i)"].to_i,params[:user][:"birth(2i)"].to_i,params[:user][:"birth(3i)"].to_i)
#    @user.birth = params[:user][:birth]
    @user.www = params[:user][:www]
    @user.about = params[:user][:about]

    @user.user_setting.update_attributes(params[:user_setting])
    Extender::Activities.update_user(@user)
    respond_to do |format|
      if @user.save
        flash[:notice] = t :saved
        format.html { redirect_to(edit_user_url) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  # GET /users/remind_password_create
  def remind_password_edit
    @user = User.new
  end

# POST /users/remind_password
  def remind_password
    @user = User.active.where(:email=>params[:user][:email]).first
    
    if @user.nil?
      flash[:user_error] = t 'users.email_not_exists_or_blocked'
      render :action => "remind_password_edit"
      return
    else
      @user.remind_token = SecureRandom.hex(18)
      @user.captcha = params[:user][:captcha]
      @user.captcha_key = params[:user][:captcha_key]
    end
    
    respond_to do |format|
      if @user.save_with_captcha
        Mailer.remind_password(@user).deliver
        flash[:notice] = t 'users.remind_password_send'
        format.html { redirect_to root_url }
      else
        format.html { render :action => "remind_password_edit" }
      end
    end
  end

  # POST /users/change_password
  def change_password
    # check hash
    @user = User.active.where(:remind_token=>params[:hash]).first
    if @user.nil?
      redirect_to root_url
      return
    end
    respond_to do |format|
      if request.post?
          @user.password = params[:user][:password]
          @user.password_confirmation = params[:user][:password_confirmation]
          @user.updating_password = true
          if @user.save
            @user.updating_password = false
            @user.remind_token = nil
            if @user.not_confirmed? # if user not active? or block?
              @user.activation_hash = nil
              @user.status = User::STATUS_ACTIVE
            end
            @user.save
            flash[:notice] = t "users.remind_password_confirm"
            format.html { redirect_to root_url }
          else
            format.html
          end
      else
        format.html
      end
    end
  end

  # GET /users/activate
  def activate
    @user = User.where(:activation_hash=>params[:hash],:status=> User::STATUS_NOTCONFIRMED).first
    respond_to do |format|
      unless @user.nil?
        @user.activation_hash = nil
        @user.status = User::STATUS_ACTIVE
        @user.save
        Extender::Activities.confirm_email(@user)
        flash[:notice] = t :user_successfully_activated
        format.html { redirect_to root_url}
      else
        format.html { redirect_to root_url}
      end
    end
  end

  def send_activation_link
    @user = User.where(:status=>User::STATUS_NOTCONFIRMED).find(params[:id])
    @user.activation_hash = Digest::SHA512.hexdigest(Time.zone.now.to_s)

    respond_to do |format|
      if @user.save
        m = Mailer.registration_confirmation(@user).deliver
        flash[:notice] = 'Wyslano link aktywacyjny'
        format.html { redirect_to :action => "edit" }
#        format.js { render_flash_window :content => 'Wyslano link aktywacyjny'}
      end
    end
  end

  def ako
    # params[:k] - api key
    # params[:opt] - option / unckeck all subscribed field / uncheck question only
    # params[:opt_id] - option id
    @user = User.active.find_by_apikey!(params[:k])
    if params[:opt] == 'sub_q' && params[:opt_id] # users/ako?k=da42j..34jnk&opt=sub_q&opt_id=11
      @thr = Thr.find(params[:opt_id])
      @thr.subscribe(@user.id) if @thr.subscribed?(@user.id)
      flash[:notice] = t "users.subscription.uncheck_thr"
      redirect_to @thr
    elsif params[:opt] == 'sub_a'
      @user.user_setting.uncheck_all_notifies
      flash[:notice] = t "users.subscription.uncheck_all"
      redirect_to @user
    else
      response_404
    end
  end

  def activity
    @user = User.active.find(params[:id])
  end

  def reputation
    @user = User.active.find(params[:id])
  end

  def votes
    @user = User.active.find(params[:id])
  end

  def favorites
    @user = User.active.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def role(integer)
    case integer
      when User::ROLE_NONE then 'nieaktywny'
      when User::ROLE_USER then 'uzytkownik'
      when User::ROLE_MODERATOR then 'moderator'
      when User::ROLE_ADMIN then 'admin'
    end
  end

  def status(integer)
    case integer
      when User::STATUS_ANONYMOUS then 'anonim'
      when User::STATUS_NOTCONFIRMED then 'niepotwierdzony'
      when User::STATUS_ACTIVE then 'aktywny'
      when User::STATUS_BLOCKED then 'zablokowany'
    end
  end

  def user_label(user)
    @user = user
    render :partial=>'users/user_label'
  end

  def user_label_small(user)
    @user = user
    render :partial=>'users/user_label',:locals=>{:small=>true}
  end

  def reputation_sign_humanized(value)
    return "plus" if value > 0
    return "minus" if value < 0
    return "zero" if value == 0
  end

  def reputation_sign(value)
    return "+" if value > 0
    return "" if value <= 0
  end

end

app/views/admin/users/change_password.html.erb
<div class="left column_main">
  <div class="title">
    <h2><%= t 'users.change_password' %></h2>
  </div>
  <div class="content">
    <p><%= t 'users.change_password_desc' %></p>
    <br />
    <%= form_for :user, :url => request.url do |f| %>
     <div class="field">
      <%= f.label t :user_password %>
      <%= f.password_field :user_password,:value=>nil %>
      <%= field_messages_for(@user,:user_password) %>
    </div>
    <div class="field">
      <%= f.label t :user_password_confirmation %>
      <%= f.password_field :user_password_confirmation,:value=>nil %>
      <%= field_messages_for(@user,:user_password_confirmation) %>
    </div>
      <%= submit_tag (t :save),:class=>"ui_button" %>
    <% end %>
  </div>
</div>  
<div class="clear"></div>

app/views/admin/users/edit.html.erb
<div class="column_main full">
  <div class="title">
    <h2><%=raw @user.sname %></h2>
  </div>
  <div class="content_padding">
    <%= form_for(@user, :url => admin_user_path(@user)) do |f| %>
      <div class="left">
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        
        <div class="field">
          <%= f.label :role %>
          <%= f.select :role, { role(1) => 1,role(2) => 2, role(3) => 3 },:selected => @user.role %>
        </div>
        <div class="field">
          <%= f.label :status %>
          <%= f.select :status, { status(1) => 1, status(2) => 2,status(9) => 9 },:selected => @user.status %>
        </div>
      </div>
      <div class="right">
        <div class="field">
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>
      </div>
      <div class="clear"></div>
      <div class="buttons">
        <%= link_to (t :cancel),admin_users_path,:class=>"ui_button _cancel" %>
        <%= submit_tag (t :save),:class=>"ui_button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div id="main">
  <div class="title">
    <h2>Uzytkownicy</h2>
  </div>
  <div id="content">
    <%= link_to 'nowy user', new_admin_user_url %>
    <table>
      <tr>
        <th><%= t "activerecord.attributes.user.sname2" %></th>
        <th><%= t "activerecord.attributes.user.email" %></th>
        <th><%= t "activerecord.attributes.user.role" %></th>
        <th><%= t "activerecord.attributes.user.status" %></th>
        <th><%= t "activerecord.attributes.user.reputation" %></th>
        <th><%= t "activerecord.attributes.user.created_at" %></th>
        <th><%= t "activerecord.attributes.user.last_login" %></th>
        <th colspan="2">Options</th>
      </tr>
      <% for user in @users %>
        <tr>
          <td><%=raw user.sname %></td>
          <td><%= user.email %></td>
          <td><%= role(user.role) %></td>
          <td><%= status(user.status) %></td>
          <td><%= user.reputation %></td>
          <td><%= distance_of_time_in_words_to_now user.created_at %></td>
          <td><%= distance_of_time_in_words_to_now user.last_login %></td>
          <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
          <td><%= link_to 'Destroy', admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div id="main">
  <div class="title">
    <h1>Nowy uzytkownik</h1>
  </div>
  <div class="content">
    <div class="desc">Po utworzeniu uzytkownika Mail nie jest wysyłany</div>
    <%= form_for([:admin,@user]) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %> &nbsp;
        <span style="height:26px;line-height:26px;" class="small_font"> (nie będzie udostepniny publicznie)</span>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="field">
        <%= f.label 'potwierdź to konto' %>
        <%= f.check_box "status",{:checked => true}, "2", "0" %>
      </div>
      <div class="field">
        <%= field_messages_for @user %>
      </div>
      <div class="actions">
        <%= link_to (t :cancel),admin_users_path,:class=>"ui_button _cancel" %>
        <%= f.submit :class=>"ui_button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/remind_password_edit.html.erb
<div class="left column_main">
  <div class="title">
    <h2><%= t("users.new") %></h2>
  </div>
  <div class="content">
    <br />
    <%= form_for :user, :url => { :action => "remind_password" } do |f| %>
      <div class="field">
        <%= f.label t :user_email %>
        <%= f.text_field :user_email %>
      </div>
      <div class="field">
        <%= flash_form_messages(:user) %>
      </div>    
      <%= submit_tag (t :send_to_email_link),:class=>"ui_button" %>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/admin/users/show.html.erb
<p>
  <b>User email:</b>
  <%=h @user.user_email %>
</p>

<p>
  <b>User password:</b>
  <%=h @user.user_password %>
</p>

<p>
  <b>User firstname:</b>
  <%=h @user.user_firstname %>
</p>

<p>
  <b>User lastname:</b>
  <%=h @user.user_lastname %>
</p>

<p>
  <b>User role:</b>
  <%=h @user.user_role %>
</p>

<p>
  <b>User last login:</b>
  <%=h @user.user_last_login %>
</p>

<p>
  <b>User street:</b>
  <%=h @user.user_street %>
</p>

<p>
  <b>User homenr:</b>
  <%=h @user.user_homenr %>
</p>

<p>
  <b>User flatnr:</b>
  <%=h @user.user_flatnr %>
</p>

<p>
  <b>User city:</b>
  <%=h @user.user_city %>
</p>

<p>
  <b>User code:</b>
  <%=h @user.user_code %>
</p>

<p>
  <b>User province:</b>
  <%=h @user.user_province %>
</p>

<p>
  <b>User status:</b>
  <%=h @user.user_status %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>